### ISSUE TITLE
Add support for imagemap output

### ISSUE THREAD

**Issue by pavarnos** [clue/graph-composer#41] opened 2018-08-04 23:04 UTC
Use http://home.mircad.nl/md/Dot_image_map.html to optionally allow an image map to be exported with the same name as the image file to make the nodes in the image clickable. When clicked, the link should go to packagist.org/packages/org-name/package-name.

**Comment by clue** [comment] 2018-10-08 08:56
@pavarnos Thank you for reporting! I agree that this features makes perfect sense.

If I'm not mistaken, this sounds like a duplicate of #22, so I'll close this ticket for help focus on the outstanding features. I'm not currently working on this, does anybody feel like working on this? PRs would be very much appreciated :+1:

**Closed by clue** 2018-10-08 08:56 UTC
Labels: help wanted, new feature
